### ISSUE TITLE
Too long show

### ISSUE THREAD

**Issue by SpaceRagnar** [teslamotors/light-show#10]
I created sequence 78 sec long but car told me its too long.
I tried to render only first 20 sec - too long
I tried to delete half of effects - too long
i tried to change mp3 onto vaw - too long
What else can be wrong?

**Comment by cmastudios** [comment]
Yeah, "too long" has a few meanings here: either that the show is longer than 5 minutes or that the show uses too much memory on the car. I would guess that your case is the latter. This can happen when the show is very complex, i.e. there's a bunch of short effects. If you are familiar with Python, you can use the `validator.py` script in this github repo to see exactly what the memory usage of the sequence is to determine how many effects you need to remove. Otherwise, there are a few recommendations at https://github.com/teslamotors/light-show#general-limitations-of-custom-shows:
- align effects to be at the same instant in time
- try using longer effects like 100ms+ if needed

**Comment by MrPaulAR** [comment]
You really need to use the validator as @cmastudios stated.  Only takes minimal effort and it'll tell you exactly the issue with your sequence.

Feel free to post your xsq file here and maybe someone will help you out but without something to help you debug there isn't much to go on.

**Comment by SpaceRagnar** [comment]
Unfortunately I can not run validator.py , but you guys right - too much effects!
At 5 am i saved "lite" version - it didn't work. But after several hours of sleep I delete couple of dozens effects and everything works!
Damn, we definitely need higher limits! My show 78 seconds long and I already should delete effects
