### ISSUE TITLE
I'm confused by the documentation regarding xLights Effect Brightness

### ISSUE THREAD

**Issue by NicholasFarseer** [teslamotors/light-show#39]
I've read the provided documentation regarding ramping light and closure channels, and am confused by how it should apply to the xLights application.
The documentation for ramping light and closure channels provide tables that list a percentage value for the brightness setting on the effect channel that changes the behavior or the light or closure. The xLights application, however, does not use a percentage value in the setting, nor does the value span 0-100 creating a de facto percentage. The brightness setting value for these effects spans 0-400 in the application, so I'm unsure how to proceed.
Should I assume that the percentage listed in the table should be considered the value to enter in the brightness field, such a 25, 50, 75, and 100? Or should I use the percentage of the full value of the setting, such as 25% = 100, 50% = 200, 75% = 300, and 100% = 400?

To make matters even more confusing, when I look at the example sequence for guidance, all of the liftgate effects have a value of 100. In fact, all of the effects in the example sequence have a value of 100, although it's obvious that different blocks in the timeline window are brighter and darker, indicating that different brightness levels have been set for them, even though they all show 100 in the color window.

Anyone else struggle with this?

**Comment by NicholasFarseer** [comment]
Oh, and this is on a Windows machine. The xLights version is 2021.40 (64 bit).

**Comment by MrPaulAR** [comment]
Set the brightness in this panel

![image](https://user-images.githubusercontent.com/3765696/148072447-845c6ce3-17f8-4bdb-86d2-4476d19f23df.png)

OR set the start and end brightness on the effect panel if using the ON effect.

![image](https://user-images.githubusercontent.com/3765696/148072585-98502295-b87a-46fe-9c96-0e74c367d5cf.png)

I have confirmed that both of the options work.

I would stick to the first option though because as you learn more about xLights you'll probably start using single line effect on groups and VU meter.

You will set the brightness to be whatever value you need based on documentation.  25, 50, etc.  The issue you are seeing is that the brightness can be set in more than one place and it stacks.  Only set it in one place.

**Comment by JVB-Tesla** [comment]
Thanks @MrPaulAR for the explanation here.
